export const fakeData = [
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Тест',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel exercitationem molestias non nemo. Corrupti, cumque tenetur dolores laborum sequi cum, et odit laudantium sed dolore impedit, vel est odio mollitia!',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Тест',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Тест',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Тест',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Тест',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Тест',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Тест',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
    {
        priority: 'Средний',
        status: 'В работе',
        taskName: 'Тест',
        aboutInfo: 'Тест',
        dateOfCreate: '26.06.2025',
        lastModifiedDate: '26.06.2025',
        dateOfClose: '26.06.2025',
        docs: [],
        author: 'Тест',
    },
]