export interface MovieSchema {
    id: string,
    title: string,
    originalTitle: string,
    language: string,
    releaseYear: number,
    releaseDate: string,
    genres: string[],
    plot: string,
    runtime: number,
    budget: null,
    revenue: null,
    homepage: string,
    status: string,
    posterUrl: string,
    backdropUrl: string,
    trailerUrl: string,
    trailerYouTubeId: string,
    tmdbRating: number,
    searchL: string,
    keywords: [],
    countriesOfOrigin: [],
    languages: [],
    cast: [],
    director: string,
    production: null,
    awardsSummary: null,
}

